CREATE TABLE IF NOT EXISTS "posts" (
    "id" BIGSERIAL UNIQUE NOT NULL, 
    "title" TEXT, 
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);